# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A project for learning about edge computing."
language = "javascript"
manifest_version = 3
name = "Hello Compute"

[local_server]

  [local_server.backends]

    [local_server.backends.website]
      url = "http://localhost:3000/"

[scripts]
  build = "npm run build"
  post_init = "npm install"
